model_name: "LNN_1"
batch_size: 256
num_max_epochs: 20
early_stopping:
  monitor: validation_mse_epoch
  patience: 6
optimizer:
  lr: 0.0005
  weight_decay: 0.001
scheduler:
  patience: 2
  factor: 0.2
  monitor: validation_mse_epoch